### ISSUE TITLE
Issue setting up local with lando

### ISSUE THREAD

**Issue by rick02840** [hackforwesternmass/lightupthemap#10]
Steps to reproduce:
1. cloned the git repo into a folder  (note I think this step needs to be added to readme?)
2. cd into that folder
3 run `lando start`
... a lot of stuff gets installed, ending in this:
```
├── matchdep@1.0.1 (stack-trace@0.0.9, resolve@1.1.7, findup-sync@0.3.0, micromatch@2.3.11)
├── liftoff@2.3.0 (lodash.isstring@4.0.1, lodash.mapvalues@4.6.0, rechoir@0.6.2, extend@3.0.1, flagged-respawn@0.3.2, resolve@1.4.0, fined@1.1.0, findup-sync@0.4.3)
└── semver-greatest-satisfied-range@1.1.0 (sver-compat@1.5.0)
npm info ok
```
4. It just sits there....  anything else I need to do, or is above wrong?

**Comment by serundeputy** [comment]
@rick02840 try ctrl+c; then try to visit: lightupthemap.lndo.site

**Comment by rick02840** [comment]
I left for a while, and when I came back it was this:
```
BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME      lightupthemap
 LOCATION  /Users/rick/Sites/light_up_github/root
 SERVICES  appserver, nginx, database, cache, edge_ssl, edge, index, node-cli
 URLS      https://localhost:32771
           http://localhost:32772
           https://localhost:32775
           http://localhost:32774
           http://lightupthemap.lndo.site
           https://lightupthemap.lndo.site
```
And this was good to go: https://lightupthemap.lndo.site/core/install.php 

So I guess it just took time.

**BOOMSHAKALAKA!!!**   ;-)

**Comment by rick02840** [comment]
Also, after running db import....

`lando db-import light-up-the-map_live_2017-08-08T23-00-00_UTC_database.sql.gz`

....the site is up and running:  https://lightupthemap.lndo.site

But then...   how to get login user/pass?  

```
lando drush uli
http://default/user/reset/1/1503870598/m_FqhS9_UO14BqQShEGXpe0rKsTFVGj2ox5PAndkffw/login
```
Then take this part:  **user/reset/1/1503870598/m_FqhS9_UO14BqQShEGXpe0rKsTFVGj2ox5PAndkffw/login**

and tack it onto https://lightupthemap.lndo.site  so:

**https://lightupthemap.lndo.site/reset/1/1503870598/m_FqhS9_UO14BqQShEGXpe0rKsTFVGj2ox5PAndkffw/login**

That got me to page user/1 page to reset password. 

BOOMSHAKALAKA!!! ;-)
