### ISSUE TITLE
User workflow documentation 

### ISSUE THREAD

**Issue by rick02840** [hackforwesternmass/lightupthemap#17]
I thought we needed an issue to discuss the exact user workflow we are looking for so we are all on the same page, as opposed to just a mention of it in this issue: 
 https://github.com/hackforwesternmass/lightupthemap/issues/3

**Comment by rick02840** [comment]
Is this the workflow wanted?

1. User picks an action, either from a list, or a featured action on the home page.

2. Clicking (choosing) the action takes the user to a page (or popup) that explains what the user needs to do to take the action. 

3. On that page will be a button to “put my light on the map” (or whatever) to be done after the user has taken the action.  

4. Clicking that button opens the light creation form with the action the user chose pre-filled (optionally that is a hidden field).

5. The form asks for location. When the user enters location, the state rep and senator fields are auto-filled-in via an API.  This location is used to place the light on the map.

6. Optionally, the form asks for an email address, so that the light can be associate with the user.

7. On clicking the submit button the user is redirected to _________ ?   suggestion: to a page that shows the light just created and a user account creation / login form. 

Note: in all of the above “user” is not logged-in (yet) and may or may not already have a user account on the site.  Also: "action" and "light" are content types on the Drupal site.

**Comment by a-pasquale** [comment]
That is the idea. The initial implementation is in the [11-rest-create-lights](https://github.com/hackforwesternmass/lightupthemap/tree/11-rest-create-lights) branch. On submitting a light, the light is created by ajax POST to REST endpoint and the node id is returned with the response. The light is also added to the leaflet map immediately. 

Light nodes ids created while anonymous are currently stored as an array in the browser's localStorage. An anonymous visitor might create multiple lights by calling both representative and senator.

When the visitor is done, they click a button to look at the map and see the light(s) they have created along with all the other lights. There is an option from there to register for an account, which then prompts for account information. Account creation via REST is working currently. 

We need to determine how to update those new anonymous lights with the new user id, linking them to the newly registered account. Passing the node ids with account creation could work. Hook into account registration would need to check any node ids that were posted to confirm they are anonymous before replacing anonymous user id (0) with the new user id.
