### ISSUE TITLE
Add .lando.yml config file for local dev stack and tooling.

### ISSUE THREAD

**Issue by serundeputy** [hackforwesternmass/lightupthemap#5]

**Comment by serundeputy** [comment]
@rick02840 PR: https://github.com/hackforwesternmass/lightupthemap/pull/9

This adds the `.lando.yml` file to allow Lando to manage the tooling for the project.  As a consequence I've  removed all the `node_modules` from the theme and added a build step to the `.lando.yml` file so all developers will have the right node, npm and node_modules to work with the lightupthemap app.

I've moved the `gulpfile.js` file to the root of the project so you can run your `drush`, `gulp` and `drupal` (Drupal Console) commands from the root of the project.

----
There is  a bug either in `lando` or the `lightupthemap` app that prevents lando from starting correctly which is unfortunate, but I've not been able to isolate it.  It results in a loop when lando is starting:

```bash
info: Checking to see if http://lightupthemap.lndo.site is ready.
info: Checking to see if https://lightupthemap.lndo.site is ready.
info: Checking to see if http://localhost:32793 is ready.
info: Checking to see if https://localhost:32796 is ready.
info: Checking to see if http://localhost:32793 is ready.
info: Checking to see if https://localhost:32796 is ready.
info: Checking to see if http://localhost:32793 is ready.
info: Checking to see if http://localhost:32795 is ready.
info: Checking to see if https://localhost:32796 is ready.
info: Checking to see if http://localhost:32793 is ready.
info: Checking to see if https://localhost:32796 is ready.
```

Once you see it repeating the `localhost` URLs it is safe to `Ctrl+c` it and use the app as normal probably via the `https://lightupthemap.lndo.site` URL.

command:

  * To Start: `lando start`
  * To stop: `lando stop`
  * compile and watch SASS: `lando gulp`

----

* d47c6df72 - (HEAD -> 4-add-lando-config) .lando.yml services and tooling config. (8 days ago) <Geoff St. Pierre>
* 76439a43d - #4: Add .lando.yml and move package.json and gulpfile.js to root of project. (12 days ago) <Geoff St. Pierre>
* 528cfb8f4 - #4: Configure git to ignore node_modules and add instructions to REAMDE to use lando dev stack. (12 days ago) <Geoff St. Pierre>
* 53104c4ac - #4: Remove node_modules from the theme. (12 days ago) <Geoff St. Pierre>

**Comment by rick02840** [comment]
Hi Geoff,
I synced things up so that Pantheon master and Github master have the same files.
I went to work on my local and gulp did not work.
I ran **npm install** from the site root and **gulp watch** worked after that.
Was that the right thing to do (npm install)?  If so I should probably add it to the README for anyone who does a non-lando local setup.
Thanks,
Rick

**Comment by serundeputy** [comment]
yes. If you are running `lando` it manages the js for you and runs `npm install` for you.

If you are not using lando; you need to manage and run `npm install` yourself.
