### ISSUE TITLE
Use email as username

### ISSUE THREAD

**Issue by rick02840** [hackforwesternmass/lightupthemap#6]
Use email as username to speed up user account creation.

**Comment by rick02840** [comment]
This?  https://www.drupal.org/project/email_registration

**Comment by andyanderson** [comment]
That looks good. There are a couple of others listed as conflicts that might provide the same service, but I don’t know which one is “best”.

— Andy

On Sep 3, 2017, at 11:21 AM, Rick Hood <notifications@github.com<mailto:notifications@github.com>> wrote:


This? https://www.drupal.org/project/email_registration

**Comment by rick02840** [comment]
Branch for this:  **github-issue-6** 
Installed module, configured, exported config (is committed to that branch)
Merged branch into **rick** branch, pushed to rick environment.  
It all worked fine. Will push to staging, then dev > test > live later.

**Comment by rick02840** [comment]
This is deployed to live (the `master` branch which is used in dev, test and live environments on Pantheon):  www.lightupthemap.com
It is also deployed to `staging` and `rework`:
staging-light-up-the-map.pantheonsite.io 
rework-light-up-the-map.pantheonsite.io

So user accounts can now be created with email only and login with email rather than username (username is auto, and can be changed later) .

Note: as a reminder, `rework` is the branch I created to do all the testing for the work that is mainly being done in  in `11-rest-create-lights` (Geoff) and  `github-issue-3` (me).  Because that work is so "major" I thought it deserved its own branch and environment (e.g. not use `staging` for that). 
Also, in issue 11, Geoff has suggested: "We can merge @rick02840 's `branch github-issue-3` into the branch for this isssue `11-rest-create-lights`".  I will do that now, if it has not already been done.
